config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    post 'vote'
  end
  resources :comments
  devise_for :admins
  devise_for :users, controllers: { registrations: "users/registrations" }   

  resources :posts
  devise_scope :user do
  get '/users' => 'users/registrations#index', as:'index_user_registration'
  get '/users/:id' => 'users/registrations#show', as:'show_user_registration'
  delete '/users/:id' => 'users/registrations#destroy', as:'delete_user_registration'
  end 
  
  root 'posts#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings

	scope :eager_scope , ->{includes(:votes)}
	scope :recent_posts, -> {order(created_at: :desc)}
	scope :upvoted_posts, ->{order(upvote_count: :desc)}
	scope :commented_posts, ->{order(comments_count: :desc)}
	scope :viewed_posts, ->{order(impressions_count: :desc)}
	
	scope :last_month, ->{where(created_at: 1.months.ago..DateTime.now)}
	scope :last_week, ->{where(created_at: 1.weeks.ago..DateTime.now)}
	scope :last_day, ->{where(created_at: 1.days.ago..DateTime.now)}
	scope :last_hour, ->{where(created_at: 1.hours.ago..DateTime.now)}

	is_impressionable :counter_cache => true, :unique => :user_id
	belongs_to :user
	has_many :votes, as: :voteable
	validates :user_id, presence:true
	validates :avatar, presence:true
	has_attached_file :avatar, 
	:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
	:url => "/system/:attachment/:id/:basename_:style.:extension",
	:styles => {
	  :thumb    => ['x300', :jpg],
	  :original    => ['100x1080^',      :jpg]
	  
	},
	:convert_options => {
	  :thumb    => '-set colorspace sRGB -strip -quality 80',
	  :original   => '-set colorspace sRGB -strip -quality 60'
	}
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	def total_votes
    	self.up_votes + self.down_votes
 	end
  
  	def up_votes
  	  self.votes.where(vote: true).size
 	end

 	def vote_score
 	  self.up_votes - self.down_votes
 	end
  	
 	def down_votes
  	  self.votes.where(vote: false).size  
 	end

 	def all_tags=(names)
	  self.tags = names.split(",").map do |name|
	      Tag.where(name: name.strip).first_or_create!
	  end
	end
 
	def all_tags
	  self.tags.map(&:name).join(", ")
	end

	def self.tagged_with(name)
		begin
		  Tag.find_by_name!(name).posts
		rescue
		  return nil
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_permission, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  helper_method :show_post2
  impressionist :action=> [:show], :unique => [:impressionable_type, :impressionable_id, :session_hash]
  # GET /posts
  # GET /posts.json
  def index
    @posts= Post.all
    if params[:tag].present?
      begin
          @filter="hello"
          @posts=@posts.tagged_with(params[:tag]).send(params[:sort_id])
      rescue
          flash[:notice] = "No posts for your search tag found."
      end
    end
    if params[:filter_id].present?
      @filter="hello"
      @posts=@posts.send(params[:filter_id])
    else
      @posts=@posts.last_month
    end
    
    if params[:sort_id].present?
       @filter="hello"
       @posts=@posts.send(params[:sort_id])
      
    else
      @posts=@posts.upvoted_posts

    end
    @posts=@posts.page(params[:page]).per(18)
    @tags= Tag.all.order_count
    
  end
 
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.user_name = current_user.name
    #  @post = Post.new(post_params)
   # respond_to do |format|
      if @post.save
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
        #format.json { render :show, status: :created, location: @post }
        render json: { message: "success", fileID: @post.id }, status: 200
      else
        render json: { error: @post.errors.full_messages.join(',')}, status: 400
        #format.html { render :new }
        #format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def vote
    @post = Post.find(params[:post_id])
    #if you already have before_action set up for the preceding line, you can just add :vote there
    vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    #strong params not needed because keys are hard coded, can parse values out
      if vote.valid?
        if vote.vote?
          Post.increment_counter(:upvote_count,@post.id)
        else 
          Post.increment_counter(:downvote_count,@post.id)
        end
        flash[:notice] = "Your vote was counted."
      else
        flash[:notice] = "You can only vote once."
      end
      respond_to do |format|
      #format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      #format.json { head :no_content }
      format.js
       end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :avatar, :sort_id, :filter_id,:all_tags)
    end
    def require_permission
      if user_signed_in?
        if current_user != Post.find(params[:id]).user
          if !admin_signed_in?
          redirect_to :root, notice: "Access Denied."
          end
        end
      else
        if !admin_signed_in?
          authenticate_user!
        end
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_cloud(tags, classes)
	  max = tags.sort_by(&:count).last
	  tags.each do |tag|
	    index = tag.count.to_f / max.count * (classes.size-1)
	    yield(tag, classes[index.round])
	  end
	end
end

app/views/posts/_blackheart.html.erb
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 42.78 42.78" style="enable-background:new 0 0 42.78 42.78;" xml:space="preserve">
<g>
	<path class="black_heart" transform="rotate(180 21.4 21.4)" style="" d="M17.745,37.992c2.575,1.38,6.947,1.194,9.433-0.342c5.924-3.661,15.429-11.039,15.429-20.715
		c0.063-0.597,0.15-1.2,0.15-1.827c0-6.224-5.047-11.274-11.274-11.274c-4.458,0-8.274,2.611-10.105,6.364
		c-1.83-3.753-5.647-6.364-10.104-6.364C5.047,3.834,0,8.885,0,15.108c0,0.653,0.085,1.287,0.194,1.907
		c-0.033,0-0.013,0.085,0.02,0.222c0.178,0.928,0.485,1.8,0.875,2.632C2.771,24.145,7.192,32.339,17.745,37.992z"/>
</g>

</svg>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true, class: "dropzone"}) do |f|  %>
  <div class="field">
    <%= f.label "title:"%>
    <%= f.text_field :title %>
    <%= f.label "Tags:"%>
    <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
    
  </div>
  <div class="fallback">
    <%= f.file_field :avatar %><br>
    <%= f.submit "Upload my Avatar" %>
  </div>
<% end %><br>
<button id="imgsubbutt">Submit all files</button>

app/views/posts/_index.html.erb
<% @posts.each do |post| %>
    <div class="thumb">
   

	    <%=link_to image_tag(post.avatar.url(:thumb)), post %>
	    <div class="subtitle">
	    <span class="vote_left"><%= post.upvote_count%> <%= render 'posts/svgheart'%>
	    <span class="whitespace"></span>
	    <%= post.downvote_count%> <%= render 'posts/blackheart'%>
	     </span>
	    <span class="user_right"><%=link_to post.user_name, show_user_registration_path(post.user_id),:class=>:show %>
	    </span>
	    </div>
	    <div style="clear: both;"></div>
	    
   		 
    </div>
         
    
<% end %>

app/views/posts/_indexgrid.html.erb
<% posts.each do |post| %>
    
   
<div class="thumb2">
   

	    <%=link_to image_tag(post.avatar.url(:thumb)), post %>
	    <div class="subtitle">
	    <span class="vote_left"><%= post.upvote_count%> <%= render 'posts/svgheart'%>
	    <span class="whitespace"></span>
	    <%= post.downvote_count%> <%= render 'posts/blackheart'%>
	     </span>
	    <span class="user_right"><%=link_to post.user_name, show_user_registration_path(post.user_id),:class=>:show %>
	    </span>
	    </div>
	    <div style="clear: both;"></div>
	    
   		 
    </div>
	   
	    
   		 
  
         
    
<% end %>

app/views/posts/_newPostButton.html.erb
<% if user_signed_in? %>
	 
	<%= link_to 'New Post', new_post_path, :"data-no-turbolink" => true %>
		
<% end %>

app/views/posts/_postEdit.html.erb
<%if current_user == @post.user or admin_signed_in?%>
  | 
  <%= link_to "delete", @post, :method=>:delete, :class=>:destroy , data: {confirm: "Are you sure?"}  %> |
  <%= link_to 'Edit', edit_post_path(@post) %> |

<%end%>

      

app/views/posts/_svgheart.html.erb
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 42.78 42.78" style="enable-background:new 0 0 42.78 42.78;" xml:space="preserve">
<g>
	<path class="heart" style="" d="M17.745,37.992c2.575,1.38,6.947,1.194,9.433-0.342c5.924-3.661,15.429-11.039,15.429-20.715
		c0.063-0.597,0.15-1.2,0.15-1.827c0-6.224-5.047-11.274-11.274-11.274c-4.458,0-8.274,2.611-10.105,6.364
		c-1.83-3.753-5.647-6.364-10.104-6.364C5.047,3.834,0,8.885,0,15.108c0,0.653,0.085,1.287,0.194,1.907
		c-0.033,0-0.013,0.085,0.02,0.222c0.178,0.928,0.485,1.8,0.875,2.632C2.771,24.145,7.192,32.339,17.745,37.992z"/>
</g>

</svg>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="fixed_right_pane">
<%= form_tag("/posts", method: "get") do %>
  <%= select_tag(:sort_id, options_for_select([['views', "viewed_posts"], ['votes', "upvoted_posts"], ['date', "recent_posts"],['comments', "commented_posts"]])) %>
   <%= select_tag(:filter_id, options_for_select([['last month', "last_month"], ['last week', "last_week"], ['last day', "last_day"],['last hour', "last_hour"]])) %>
   <br>
   <%= text_field_tag(:tag, nil , placeholder:'search tag') %>
  <%= submit_tag("Filter") %>
<% end %>
<div class="tags-cloud">
  <% @tags.each do |tag| %>
  <%=link_to  tag.name ,  posts_path( :commit => "Filter" ,:tag => tag.name, :filter_id => "last_month", :sort_id =>"viewed_posts") %>
  <%end%>
 
</div>
</div>
<div class="fixed_left_pane">
 
	<%= render 'posts/index', posts:@posts%>
 


</div>
<div style="clear:both;"></div>
<div id="bottom-button">
<button id="next-page"> load more</button>
</div>
<div class="pagination">
<%= paginate @posts %>


</div>

app/views/posts/index.js.erb
$('.fixed_left_pane').append("<%= escape_javascript render(:partial => 'index') %>");

$('.pagination').replaceWith('<%= escape_javascript  paginate @posts %>');

app/views/posts/new.html.erb
<h2>upload images</h2>

<%= render 'form' %>
<%=link_to current_user.name, show_user_registration_path(current_user),:class=>:show, id:'userPage'  %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  
<div class="left_pane">
  <div class="image_left">

	<%= image_tag @post.avatar.url %>
   <div class="right_pane">
tags :

  <% @post.tags.each do |tag|%>
    <%=link_to  tag.name ,  posts_path( :commit => "Filter" ,:tag => tag.name, :filter_id => "last_month", :sort_id =>"viewed_posts") %> ,
  <%end%>
  <br>
  <%show_post=false%>

  <%=render 'comments/form' , post:@post%> 
  <% @current_comments= @post.comments.eager.recent_comments%>
  Comments:
  <div class="comments_show">
  <%=render 'comments/show' , comments:@current_comments, show_post:show_post%> 
  </div>
  </div>
</div>

<div style="clear: both;"></div><br>
<div class="subtitle-show">
     
      <%= link_to post_vote_path(@post, vote: true), method: 'post' , remote: true do %>
   <%=render 'svgheart'%>
   <%end %>
   <span id="upvotecount">
    <%= @post.upvote_count %> </span>
         <span class="whitespace"></span>
    <%= link_to post_vote_path(@post, vote: false), method: 'post', remote: true  do %>
      <%=render 'blackheart'%>
      
    <%end %> <span id="downvotecount">
    <%= @post.downvote_count %> </span>
    <span class="whitespace"></span>
    <%= render 'posts/postEdit'%> <%= @post.impressions_count %> views <span class="whitespace"></span> <%= @post.comments_count %> comments <span class="whitespace"></span> 
       </span>
       <span class="whitespace"></span>
      <span class="user-right-show"> @ <%=link_to @post.user_name, show_user_registration_path(@post.user),:class=>:show %>
      </span>
      <span class="whitespace"></span>
      <button class="zoomin"> +
      </button>
      <span class="whitespace"></span>
      <button class="zoomout"> -
      </button>
       <span class="whitespace"></span>
      <button class="reset"> []
      </button>
    </div>

	 
   
</div>


<div style="clear:both;"></div>

 

 

app/views/posts/vote.js.erb
$('#downvotecount').html("<%= @post.downvote_count%>");
$('#upvotecount').html("<%= @post.upvote_count%>");