config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    post 'vote'
  end
  resources :comments
  devise_for :admins
  devise_for :users, controllers: { registrations: "users/registrations" }   

  resources :posts
  devise_scope :user do
  get '/users' => 'users/registrations#index', as:'index_user_registration'
  get '/users/:id' => 'users/registrations#show', as:'show_user_registration'
  delete '/users/:id' => 'users/registrations#destroy', as:'delete_user_registration'
  end 
  
  root 'posts#index'
  
end

app/views/layouts/_topnav.html.erb
<div id="Logo"> IMAGER </div>
<div id="menu">
<%= link_to('home', root_path) %> <%= render 'posts/newPostButton' %>

<% if admin_signed_in? %>
	
	<%= link_to('Admin Logout', destroy_admin_session_path, :method => :delete) %>        
	 <%= link_to('user index', index_user_registration_path ) %>   
<% else %>
		
	<% if user_signed_in? %>
	 
	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
	  
	<% else %>
	  
	<%= link_to('Login', new_user_session_path)  %>  
	  
	<% end %> 
	<% if user_signed_in? %>
		
 	<%= link_to('Edit registration', edit_user_registration_path) %>
		
	<% else %>
		
	<%= link_to('Register', new_user_registration_path)  %>
		
	<% end %>
		
<% end %>
</div>
<div id="notice">
<%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freshimg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class= 'top_bar'> 
	<%= render 'layouts/topnav' %>
</div>
<div class= 'content'> 
	<%= yield %>
</div>


</body>
</html>